### ISSUE TITLE
The whole system's configuration seems in error

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-pnp-exampleco-timesheets#7]
While I love the idea of this system with three participating apps (node, javascript and python) I found at least one error:

The port number for [API-URL](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-cron/python/cron.py#L9) should be 4020 - not 8080 as it is currently defined.

Even with this fix, trying to run python [cron.py](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-cron/python/cron.py#L9) program, I get

```
λ python cron.py
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJqWkJOVFkyTnpSQk5VVTVSakF5TkVZeFJEbEZSRUV4T0RWQlJFSTFOVUl4UmpOR1JEQkJPUSJ9.eyJpc3MiOiJodHRwczovL2F1cmVsaWF0b29scy5hdXRoMC5jb20vIiwic3ViIjoibzRVMFEwVEFra080aEJ1aW1EaUI2d1ZseUtGVWRrM2dAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vYXBpLmF1cmVsaWF0b29scy5jb20vdGltZXNoZWV0cyIsImV4cCI6MTQ5ODMxODYyNCwiaWF0IjoxNDk4MjMyMjI0LCJzY29wZSI6IiJ9.LVjCE69BHB2n_vVLSb1oamQsxgBtQGNgO0_wZYdJOWfzCjYUfL5gsjBe2cXnv2V2dQZAF8UHmYiSU16sBrN7YntpjrnpsGfep4PswmaMekxY8SymhVErlrZMspQCtdHdspFd2g2eDitIG45oIZOisLV7Mw05Cl5WduBHoc28y0M4Y11zUauqHyV0KetPwhlIHsyVWwDqPT700RG4tro46fbh1q6hJEsIm8BaJ3FZeSksUlsXMpYnnwoJ5iXtByIQwoROI_NAOIXeXWXBi9nF2Ft6VrTKpIip3-zH-0Ba8vuUtYSMqtBIckvQgwXurUDX2lZsjjxD7GgvlI_oeceSRg
URLError = [Errno 10061] No connection could be made because the target machine actively refused it
```
Where I added the printout line:
```
	print 'access-token: ' + access_token
```
trying to see where the problem is taking place. It seems to be that it is the attempt to upload the stylesheet to the API (node) component.

Since I would like to help you to make sure that this **`Auth0 Server + API Sample`** works, I am attaching the sections of the code that are specific to me, so you can find what is broken. I am also doubtful whether I "nailed" all configuration data correctly; If not, assuming that I am not the dumbest Auth0 user, this might indicate the need to beef up the relevant README files and / or the 

**Python**
```
	# Configuration Values
	DOMAIN = "aureliatools.auth0.com" # Update with your Auth0 Domain
	AUDIENCE = "https://api.aureliatools.com/timesheets" # Update with the Identifier of your API
	CLIENT_ID = "o4U0Q0TAkkO4hBuimDiB6wVlyKFUdk3g" # Update with the Client ID of your Non Interactive Client
	CLIENT_SECRET = "a9UyxWSiZB1ObOVBe39_rhdmPBw_FKkQQI_WN2LH1_w8OSVATUGGBzEDetiggBZo" # Update with the Client Secret of your Non Interactive Client
	API_URL = "http://localhost:4020/timesheets/upload"
	GRANT_TYPE = "client_credentials" # OAuth 2.0 flow to use
```

**Angular**
```
  clientID: 'bpLn0Ae5NLj0117fF0wYZ61XILyZuiwB',
  domain: 'aureliatools.auth0.com',
  callbackURL: 'http://localhost:4200/callback',
  silentCallbackURL: 'http://localhost:3001/silent',
  apiUrl: 'https://api.aureliatools.com/timesheets'
```

**Node - .env**
```
AUTH0_DOMAIN=aureliatools.auth0.com
AUTH0_AUDIENCE=o4U0Q0TAkkO4hBuimDiB6wVlyKFUdk3g
```
***
@chenkie - copying Ryan as I am not sure about Jerrie's frequency of issues checking 😄

**Comment by adriatic** [comment]
Added later - once I observed that I am getting errors on **`node server`** command running console:
```
λ node server
Listening on http://localhost:8080
UnauthorizedError: jwt audience invalid. expected: o4U0Q0TAkkO4hBuimDiB6wVlyKFUdk3g
    at H:\work\aurelia-auth0\auth0-pnp-abc-timesheets\timesheets-api\node\node_modules\express-jwt\lib\index.js:102:22
    at H:\work\aurelia-auth0\auth0-pnp-abc-timesheets\timesheets-api\node\node_modules\jsonwebtoken\verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This tells me that the JWT token fails verification - **`jwt audience invalid`**. As I currently understand this situation the **`audience`** is tied to **[this definition](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-spa/angular/src/app/auth/auth0-variables.ts.example#L6)** - and this does not seem right.

So, awaiting for Jerrie's resolution - anxiously 😏

**Comment by jerriep** [comment]
@adriatic I will look into all these issues of yours, but please be patient. I need to juggle this with my other tasks.

Is this causing you production issues, or are you merely looking into this out of curiosity?

Also, you need to understand that these samples should be consumed in conjunction with the actual Architecture Guidance documents:
* https://auth0.com/docs/architecture-scenarios/application/web-app-sso
* https://auth0.com/docs/architecture-scenarios/application/server-api
* https://auth0.com/docs/architecture-scenarios/application/spa-api

That being said, it is no excuse for the samples not working correctly. I will look into this

**Comment by jerriep** [comment]
> The port number for API-URL should be 4020 - not 8080 as it is currently defined.

The API is indeed running on port `8080`: 
https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-api/node/server.js#L80

Port `4020` is not used anywhere. I assume it is a typo on your side and you mean `4200`? But that is the port for the Angular application. You should not try and point the Python cron job there, because you will not have any success.

I made some other small fixes, so please pull latest changes. You error however from what I can see is 2 fold:

1. The `API_URL` (now renamed to `api_url`) is wrong. It should be `http://localhost:8080/timesheets/upload`
2. In the API (Node app), you have a wrong value for `AUTH0_AUDIENCE`. As stated by the README it should be the value of your API Identifier, so in other words `https://api.aureliatools.com/timesheets`

**Comment by adriatic** [comment]
@jerriep Thanks for addressing my questions - explanations on my motivations do not necessarily fit the contents of GithHub issues conversations, so I will send you (and @chenkie) an email why am I doing what I am doing.
